### ISSUE TITLE
custom posisi widget

### ISSUE THREAD

**Issue by laksonoadi** [fathulhudoyo/sample_widget_aksesbilitas#3]
by default, button widget ada di sebelah kiri, apa mungkin ke depan ditambahkan fitur untuk custom posisi buttonnya ?

**Comment by fathulhudoyo** [comment]
untuk nextnya nanti akan saya tambahkan mas agar bisa pindah posisi letak widgetnya,  

untuk sementara kalau mas ada request letak widget kasih tahu link webnya nanti saya buat pengecualian buat webnya 🙏 .

untuk source code bisa ke sini mas  https://github.com/fathulhudoyo/Fitur_Disabilitas.

**Comment by laksonoadi** [comment]
web slemankab.go.id mas. mohon bantuannya, biar bisa posisi di kanan. karena di kiri sudah ada icon lain. trims

**Comment by fathulhudoyo** [comment]
ok siap, cek lagi mas [laksonoadi](https://github.com/laksonoadi) sudah ada di kanan ya 🙏
